### PR TITLE
Alert levels

### PR DESCRIPTION
**Pull request by GitHubUser53123**
## About the PR

Adds 3 new admeme alert levels!
## Why / Balance

New alert levels!
## Technical details
Nay.
## Media

https://github.com/Verbalase/Goob-Station/assets/110841413/000202ec-45df-4c93-944e-b83d641983dd

- [✓] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by GitHubUser53123** [comment]
Ignore the conflict, it's fucking delusional.
image

**Review by BYONDFuckery — APPROVED** [review]
Merge.

**Comment by quri1q** [comment]
add sigma alert level

**Comment by GitHubUser53123** [comment]
Swiss cheese.

**Comment by GitHubUser53123** [comment]
Shitpost

**Pull request closed without merging**
