### PR TITLE
Syndicateboomox

### PR DESCRIPTION
**Pull request by zmanprodigy**
adds the syndicate boombox, it blasts ultrakill music at your foes when bought for 2 TC.

also adds weh juice... again...

### CODE REVIEW

**Comment by CatMagic1** [comment]
seems legit

**Comment by CatMagic1** [comment]
also whart about my sprites :(

**Comment by zmanprodigy** [comment]
> also whart about my sprites :(

i added ur sprites :DD

**Comment by zmanprodigy** [comment]
ermmm... what the flip? it didnt save

**Comment by zmanprodigy** [comment]
meant to put (Thanks cat!!) as description

**Pull request merged**
