### PR TITLE
1 line change.

### PR DESCRIPTION
**Pull request by BYONDFuckery**
BOT WANTS ME TO COMMIT FROM HERE RAHHH

URANIUM REAGENT IS GETTING AXED
WE USE MUTAGEN INSTEAD

### CODE REVIEW

**Comment by BYONDFuckery** [comment]
bot hasen't axed the PR yet. feeling good

**Comment by BYONDFuckery** [comment]
perchance this is our 40th closed PR
**that would be gamer**

**Comment by BYONDFuckery** [comment]
YAML Linter may or may not be failed currently (my fault)
The other failing check is NOT my fault.

**Comment by BYONDFuckery** [comment]
2 line change 💀

**Comment by BYONDFuckery** [comment]
currently build and test debug is currently screwed (and its not my fault)

**Comment by BYONDFuckery** [comment]
after "rewriting" the recipe, (deleting and copy and pasting another one) it should work

**Comment by BYONDFuckery** [comment]
This isn't my fault, time to revert.

**Comment by BYONDFuckery** [comment]
i have resorted to ChatGPT (it worked)

**Comment by Verbalase** [comment]
merge?

**Comment by BYONDFuckery** [comment]
> merge?

not ready - let me fix this bug.

**Comment by BYONDFuckery** [comment]
this should be almost ready.

**Comment by BYONDFuckery** [comment]
It was not in fact, almost ready.

**Comment by BYONDFuckery** [comment]
@Verbalase works

**Pull request merged**
