### PR TITLE
Goob chatsan changes

### PR DESCRIPTION
**Pull request by Hmeister-real**
## Why / Balance
 Ton of new chatsans, however don't look at the changes for it will spoil the secret of finding them in game ooo. I also want to hmeisterfrfr post in ooc for a short time untill it gets abused and il then revert it

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
 the funny is real, but i really just wanted kys to be a thing and then started messing around lol

**Changelog**

:cl: Hmeister

- tweak: You can now tell people to keep themselves safe (kys) and also some other secret phrases you'll have to discover yourself.

### CODE REVIEW

**Comment by Hmeister-real** [comment]
Oh yeah, this also merges upstream, woops

**Comment by Hmeister-real** [comment]
Failures are unrelated i think

**Comment by CatMagic1** [comment]
censor all the gen alpha slang

**Comment by Hmeister-real** [comment]
> censor all the gen alpha slang

can you review and pinpoint which?

**Comment by CatMagic1** [comment]
add censors for them

**Comment by Hmeister-real** [comment]
> add censors for them

i mean which slang specifically?

**Comment by CatMagic1** [comment]
gyatt
rizzler
fanum tax
skibidi

replace them all with [1984'd]

**Comment by Hmeister-real** [comment]
> gyatt rizzler fanum tax skibidi
> 
> replace them all with [1984'd]

ok later, let me binge Avatar last airbender first

**Comment by Verbalase** [comment]
codebend

**Pull request merged**
