### PR TITLE
Librarian content

### PR DESCRIPTION
**Pull request by CatMagic1**
## About the PR
don't merge don't merge not done
i don't wanna lose my changes so here
and my vs is FUCKING DUCK FUCK DUKC FUCK FUCK
i've been trying to test my changes for the past 2 days
## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by BYONDFuckery** [comment]
Draft PR:

**Review by BYONDFuckery — CHANGES_REQUESTED** [review]
maybe fix the pen to put something like the bartender drink and add a cool down, the current iteration is abusable

**Comment by BYONDFuckery** [comment]
and make all the other pens embeddable

**Comment by CatMagic1** [comment]
all the other pens inherit from the base pen so they embed too
I'm like REALLY new to yml so if that isn't how that works oops
but i'm like pretty sure that's how it works

**Comment by CatMagic1** [comment]
also the pen only contains and inject 3u of space drugs so that should be used up on one throw
once again if that isn't how it works tell me

**Comment by Verbalase** [comment]
You are pulling some other stuff I don't want merged...

**Pull request closed without merging**
