### PR TITLE
Blackburn plushies, mask and uniform

### PR DESCRIPTION
**Pull request by toasterpm87**
## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by toasterpm87** [comment]
**BIG PROBLEM** i can't make a dev environment so one of you poor fuckers are gonna have to test it or merge it raw

**Comment by toasterpm87** [comment]
those conflicts are changed i never made soooo *shrug*

**Comment by CatMagic1** [comment]
why can't make dev environment

**Comment by toasterpm87** [comment]
> why can't make dev environment

the cmd stopped being nice but its not from the code, i think it can't find what its trying to activate

**Comment by toasterpm87** [comment]
bkv1
bkv2
foxmaskfull
foxicon
equipped-INNERCLOTHING
icon

**Comment by Verbalase** [comment]
Conflicts and I don't want those other changes added.

**Comment by GitHubUser53123** [comment]
Nuh uh plyush!!!

**Pull request closed without merging**
