### PR TITLE
Ert gun

### PR DESCRIPTION
**Pull request by RealFakeSoof**
## About the PR

Added a laser gun for ERT Chaplain
## Why / Balance

Regular Chaplain has one, so ERT Chaplain should have a better one too. 
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/Verbalase/Goob-Station/assets/131112412/b723c91f-5711-46ae-856f-df43c6facf0e

**Changelog**

:cl:
- add: Gave ERT Chaplain a gun!
- remove: Removed the useless flare from ERT Chaplain's inventory!

### CODE REVIEW

**Comment by roighteously** [comment]
Yeah this guys goated so yeah

**Review by roighteously — APPROVED** [review]
Fire!

**Comment by Verbalase** [comment]
Must pass all checks.

**Comment by Verbalase** [comment]
Well, atleast what I was told..

**Comment by roighteously** [comment]
Hi Real fake soofle Congraultions on the pull rqest being  Merged....

However, the Ubuntu check failing is not due to your code but I heard that space stantion 13

**Pull request merged**
