### PR TITLE
Vox uniquities

### PR DESCRIPTION
**Pull request by CatMagic1**
## About the PR

Voxes are now generally less affected by poison, rads, caustic, and genetic damage but are more vulnerable to slash and bloodloss
it's pretty okay, not having to worry about poison and rad bs is fun
## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by CatMagic1** [comment]
ready for merge
i'll make another pr if I can think of something else to add later

**Comment by Verbalase** [comment]
I should deny this for your small unfunny jokes

Merged.

**Comment by Verbalase** [comment]
Never mind, Github refuses to let me merge for some reason.

**Comment by CatMagic1** [comment]
it WAS drafted but it now open so I dunno why it wouldn't let you merge

**Comment by Verbalase** [comment]
merged

**Pull request merged**
