### PR TITLE
Cream pie cannon

### PR DESCRIPTION
**Pull request by GitHubUser53123**
image

https://github.com/Verbalase/Goob-Station/assets/110841413/6a9090c6-ee00-41e7-9061-41a992e14a1f

### CODE REVIEW

**Comment by GitHubUser53123** [comment]
Uhoh, included my previous PR in this one

**Comment by GitHubUser53123** [comment]
Fixed!

**Comment by Verbalase** [comment]
Isn't this kinda overpowered since it stuns and makes people drop their shit constantly or nah.

**Comment by Verbalase** [comment]
actually fuck it

load the album

**Comment by Verbalase** [comment]
also fuck you for changing the secret weights

**Pull request merged**
