### PR TITLE
PLEASE

### PR DESCRIPTION
**Pull request by CatMagic1**
## About the PR

AGHHHHHHHHHHHHHHHHHHHHHHH
CATS AND THRONGLES
## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Hmeister-real** [comment]
make cat ears 1 tc :trollface:

**Comment by CatMagic1** [comment]
> make cat ears 1 tc :trollface:

i would've but it'd undervalue them

**Comment by CMDR-Piboy314** [comment]
if I get every syndi on the station together....

**Comment by Verbalase** [comment]
Conflicting files. Fix it.

**Comment by CatMagic1** [comment]
mothergucker

**Comment by Verbalase** [comment]
Conflicts, fix them.

**Pull request closed without merging**
