### PR TITLE
Jukebox Songs 2 electric boogaloo

### PR DESCRIPTION
**Pull request by Hmeister-real**
## About the PR
Even more songs, not just Fallout ones this time. No shitposts

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Hmeister
tweak: Jukebox now has even more songs!

### CODE REVIEW

**Comment by Piras314** [comment]
me when I break the law

this is an insane amount of copyright infringement @Hmeister-real .....

**Comment by Hmeister-real** [comment]
> me when I break the law
> 
> this is an insane amount of copyright infringement @Hmeister-real .....

We aren't upstream, this is the equivilant of someone modding terreria with uh Nintendo characters. Copyright laws do not apply to us

**Comment by CMDR-JohnAlex** [comment]
You sometimes could add copyrighted material in your own projects for **private personal use**, but Goob Station is a **public open source github repository** and **free** game. Just because we are a fork of WizDen's Space Station 14 does not mean copyright laws no longer apply to us. **_Unauthorized use of another's copyrighted work is copyright infringement._**

> We aren't upstream, this is the equivilant of someone modding terreria with uh Nintendo characters. Copyright laws do not apply to us

Whoever is modding terreria with Nintendo characters almost certainly doesn't have permission to use their characters and could get in big trouble from Nintendo. Also, it isn't like terreria is the one adding copyrighted Nintendo characters to their game, compared to here where we are indeed adding copyrighted music to the game. Imagine playing copyrighted songs as a musician versus if we add that copyrighted music directly to the game, that is a big difference.

Also, every song you have listed you wrote as being under the copyright `CC-BY-NC-SA-3.0` yet there some quite clearly closed license songs such as "The Office Main Theme" or "Bloons TD 5 Deluxe". As well as all your sources are incorrect, it is just the Goob Station forums...

While I am not a lawyer or anything, I am 100% certain we can get in trouble for using copyrighted music and improperly licensed and credited music.

**Comment by Verbalase** [comment]
Closed due to yes, that reason. Might as well revert your other PR.

**Pull request closed without merging**
