### PR TITLE
Antag chance rebalance (and pirates too)

### PR DESCRIPTION
**Pull request by Hmeister-real**
## About the PR
 Much more likely for rat kings, ninjas, revenants, mothroaches, glockroaches :godo: and other midround antags. Also more revs, All at once and pirates!!! (maybe can't test this at all)

## Why / Balance
 Goob moment, made a thread on discord you can find and this is what i based my changes on

## Technical details
 stat changes, copy and paste mindset

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Hmeister
- tweak: Higher chance for all midround antags (also glockroaches)
- tweak: Secret now has higher chances (revs), and lower for many of the game modes (Syndicates((had to))
- add: Added Pirates, and all at once to Secret!

### CODE REVIEW

**Comment by Hmeister-real** [comment]
Also merges upstream (idk how to make it not do that)

**Comment by Hmeister-real** [comment]
The errors are unrelated to this PR, and are errors from the upstream merge that aren't actually valid, so its fine don't worry about it pinky promise :)

**Comment by Verbalase** [comment]
No.

**Comment by Hmeister-real** [comment]
any reason why?

**Pull request closed without merging**
