### PR TITLE
Fix Lingium

### PR DESCRIPTION
**Pull request by BYONDFuckery**
Also merges Upstream and fixes Lingium :3

### CODE REVIEW

**Comment by BYONDFuckery** [comment]
we're so back :3

**Comment by BYONDFuckery** [comment]
the issue was: It was using a generic id (the one for toxin) which caused conflct, and also it tastes bitter now
mmm yummy lingium.....
(10u / instant round removal lmfao)

**Comment by BYONDFuckery** [comment]
An admin with lingium walks into a bar. There is no counter.

**Comment by BYONDFuckery** [comment]
make me a maintainer... NOW!!
maints tainer

**Comment by CatMagic1** [comment]
tastes like deoxyribonucleic pain

**Comment by Verbalase** [comment]
Conflicts, fix them.

**Pull request closed without merging**
