### PR TITLE
Wizard Antagonist

### PR DESCRIPTION
**Pull request by PoTeletubby**
## About the PR
Adds Wizard Antagonist which requires 20 people to start and has the same time requirements as Nukie Commander
Adds multiple new spells + spellbooks
Adds Wizard Comms Console
Adds Wizard Stamp
Changes to the Wizard Shuttle
Adds new wizardry spellbook which acts as a type of uplink for the Wizard to buy spells

## Media

I have videos of the wizard stuff in the dev-channel of the discord
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by PoTeletubby** [comment]
EternalShibe is also me btw, I forgot to change my git stuff until like halfway through

**Comment by Verbalase** [comment]
Merged.

**Comment by CatMagic1** [comment]
i'm gonna add some shit to this because i got ideas

**Comment by Verbalase** [comment]
The antagonist role does not appear selectable.
image

image

**Pull request merged**
