### PR TITLE
Add gondolas + Tranquility

### PR DESCRIPTION
**Pull request by Aidenkrz**
Adds gondolas from SS13, they are simple mobs that cant speak, attack, and dont have hands.
They can be obtained through syndie uplink for 6 tc.
Upon butchering they give you 3 raw gondola meat, which can be cooked into gondola steak.
Both raw and cooked have the reagent Tranquility in it, which causes temporary muteness and pacifism. After digesting 30u of tranquility the player will turn into a gondola.

https://github.com/Verbalase/Goob-Station/assets/28298836/238bfb4a-3744-469b-9114-3a528e934b5f

https://github.com/Verbalase/Goob-Station/assets/28298836/8558c799-49fe-4f7e-8c44-0e49faed40ee

image

### CODE REVIEW

**Comment by BeeRobynn** [comment]
2emomhoaf1o81

**Comment by Hmeister-real** [comment]
Can't wait to turn all of command into Gondalas and turn Goob into the average Apoc station round

**Comment by Hmeister-real** [comment]
i think the meat should have 15u of tranq each, so you can duplicate free gondalas with enough effort

**Comment by Aidenkrz** [comment]
> i think the meat should have 15u of tranq each, so you can duplicate free gondalas with enough effort

raw meat has 10u so 3 raw meat = 30u of tranquility
cooked meat has 15u so 3 of those = 45u of tranq
so buy two gondolas and you can do it forever

**Comment by BeeRobynn** [comment]
> need sprites for directionals and meat?

Should be directionals to rip from tg

**Comment by Carmell0** [comment]
Can we give them a different sprite? I love the look but it’s still low def and looks… odd. Just make it a bit more high def, maybe add a walking animation?

**Comment by Aidenkrz** [comment]
> Can we give them a different sprite? I love the look but it’s still low def and looks… odd. Just make it a bit more high def, maybe add a walking animation?

> Should be directionals to rip from tg

> need sprites for directionals and meat?

FINE YOU FREAKS ILL GIVE YOU WHAT YOU WANT
image
NOW THEY HAVE DIRECTIONAL SPRITES, 3 DIFFERENT SIZES, 2 DIFFERENT MOUSTACHE TYPES, AND DIFFERENT SHADES. ARE YOU HAPPY!???

**Comment by Piras314** [comment]
if you make someone a gondola and kill the gondola do they revert? if you make someone a gondola do you get kill objective?

**Comment by Aidenkrz** [comment]
> if you make someone a gondola and kill the gondola do they revert? if you make someone a gondola do you get kill objective?

no they dont revert, and yes it counts as a kill/maroon objective when they get turned

**Pull request merged**
