### PR TITLE
Update nuke_construction.yml

### PR DESCRIPTION
**Pull request by roighteously**
## About the PR
Fix evilbombpainted crashing Ubuntu build

## Why / Balance

evilbombpainted crashing Ubuntu build
## Technical details

Change all instances of 'evilbombpainted' to 'evilbomb' which is a real id
## Media

- [x ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by roighteously** [comment]
Aww rats!

**Comment by roighteously** [comment]
**i am the alpha**

**Comment by roighteously** [comment]
> also you have the same name as me, which makes you cringe

imagine playing the game you develop for

**Comment by CatMagic1** [comment]
wait i just actually read this,
evilbombpainted IS a real id?

**Comment by CatMagic1** [comment]
do NOT merge this lemme check it real quick

**Comment by CatMagic1** [comment]
okay so switching them all to painted just makes it so they all turn into a completely different version
the REAL solution to this is to change uh

**Comment by roighteously** [comment]
> okay on further review evilbombpainted literally does exist image

why wouldn't it exist??

**Comment by CatMagic1** [comment]
> > okay on further review evilbombpainted literally does exist image
> 
> why wouldn't it exist??

also it appears you removed it in your branch

**Comment by CatMagic1** [comment]
this is superseded

**Comment by Verbalase** [comment]
Conflicting files!!!

**Comment by roighteously** [comment]
> Conflicting files!!!

What's a file?

**Comment by Verbalase** [comment]
image

**Pull request closed without merging**
